export const metadata = {
  title: "Next.js",
  description: "Generated by Next.js",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <nav className="flex flex-row justify-between px-12 py-6 text-xl">
        <div>
          <div>[Logo] Is it my turn?</div>
        </div>
        <div className="flex flex-row gap-2">
          <button className="rounded-lg bg-gray-300 hover:bg-gray-400 px-4 py-2">Open</button>
          <button className="rounded-lg bg-teal-500 hover:bg-teal-700 px-4 py-2 text-white">Create a session</button>
        </div>
      </nav>
      <body>{children}</body>
      <footer className="flex flex-row justify-evenly px-8 py-4">
        <span>© 2023 Kevin Q. Dam</span>
      </footer>
    </html>
  );
}
